replicaCount: 1

image:
  repository: k1m743hyun/member-service
  pullPolicy: Always
  tag: "latest"

application:
  server:
    port: 8080

service:
  type: ClusterIP
  port: 8080
  targetport: 8080

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

rollout:
  strategy: bluegreen
  autoPromotionEnabled: true

hostName: msa.member.com

livenessProbe:
  httpGet:
    path: /members
    port: 8080
readinessProbe:
  httpGet:
    path: /members
    port: 8080