apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
    name: {{ include "test-app.fullname" . }}-vsvc
    labels:
        {{- include "test-app.labels" . | nindent 4 }}
spec:
    hosts: # host range
    - "web.test-app.com"
    gateways: # ingress gateway
    - msa-gateway
    http:
    - match:
      - uri:
          prefix: /
      route: # routing 주소 설정
      - destination:
          host: {{ include "test-app.fullname" . }}-svc
          port:
            number: {{ .Values.service.port }}
          subset: v1
        weight: 90
      - destination:
          host: {{ include "test-app.fullname" . }}-svc
          port:
            number: {{ .Values.service.port }}
          subset: v2
        weight: 10