apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
    name: {{ include "test-app.fullname" . }}
    labels:
        {{- include "test-app.labels" . | nindent 4 }}
spec:
    hosts:
    - web.test-app.com
    gateways:
    - msa-gateway
    http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: {{ include "test-app.fullname" . }}
          port:
            number: {{ .Values.service.port }}