replicaCount: 2

image:
  repository: dstar55/docker-hello-world-spring-boot
  pullPolicy: IfNotPresent
  tag: "latest"

application:
  server:
    port: 8080

service:
  type: ClusterIP
  port: 8080
  targetport: 8080

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

rollout:
  strategy: bluegreen
  autoPromotionEnabled: false

pinpoint:
  enabled: true
  version: 2.5.1

hostName: pinpoint.test-app.com