replicaCount: 2

image:
  repository: pinpointdocker/pinpoint-quickstart
  pullPolicy: IfNotPresent
  tag: 2.5.1

application:
  server:
    port: 8080

service:
  type: LoadBalancer # ClusterIP
  port: 8081
  targetport: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

rollout:
  strategy: bluegreen
  autoPromotionEnabled: true

pinpoint:
  enabled: true
  version: 2.5.1

hostName: pinpoint.test-app.com