{{- $serviceName := include "product-grpc.name" . -}}
{{- $serviceLabels := include "product-grpc.serviceLabels" . -}}
{{- $selectorLabels := include "product-grpc.selectorLabels" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    {{- $serviceLabels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
    {{- if .Values.grpc.enabled }}      
    - port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.port }}
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{ $selectorLabels | nindent 4 }}
---
{{- if eq .Values.rollout.strategy "bluegreen" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-preview
  labels:
    {{- $serviceLabels | nindent 4 }}    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
    {{- if .Values.grpc.enabled }}      
    - port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.port }}
      protocol: TCP
      name: http
    {{- end }}      
  selector:
    {{- $selectorLabels | nindent 4 }}
{{- end }}