replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

application:
  server:
    port: 80

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetport: 80

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128

rollout:
  strategy: bluegreen
  autoPromotionEnabled: false

livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80
