replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

application:
  server:
    port: 80

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetport: 80

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

rollout:
  strategy: bluegreen
  autoPromotionEnabled: true

livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80
