apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: msa
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-charts/addon-charts/gateway
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles: 
        - {{ .Values.valueFiles }}