apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - path: helm-charts/addon-charts/istio-base
      repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
    - path: helm-charts/addon-charts/istiod
      repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}