apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-grpc
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: msa
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-charts/app-charts/product-grpc
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles: 
        - {{ .Values.msaValueFiles }}