apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: msa
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    path: helm-charts/app-charts/test-app
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}