podAnnotations:

image:
  repository: pinpointdocker/pinpoint-mysql
  tag: 2.5.1
  pullPolicy: IfNotPresent

rootPassword: root123
user: admin
password: admin
database: pinpoint

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "250m"    

affinity: {}

tolerations:

persistence:
  enabled: false
  size: 2Gi