{{- $serviceName := include "istio-test-app.name" . -}}
{{- $labels := include "istio-test-app.labels" . -}}
{{- $selectorLabels := include "istio-test-app.selectorLabels" . -}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $serviceName }}-destrule
  labels:
    {{- $labels | nindent 4 }}
spec:
  host: {{ $serviceName }}
  trafficPolicy:
      loadBalancer:
          simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      loadBalancer:
        simple: RANDOM
  - name: v2
    labels:
      version: v2
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN