{{- $serviceName := include "istio-test-app.name" . -}}
{{- $labels := include "istio-test-app.labels" . -}}
{{- $selectorLabels := include "istio-test-app.selectorLabels" . -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $serviceName }}-vsvc
  labels:
    {{ $labels }}
spec:
  hosts: # host range
  - {{ .Values.hostName }}
  gateways: # ingress gateway
  - msa-gateway
  http:
  - match:
    - uri:
        prefix: /
    route: # routing 주소 설정
    - destination:
        host: {{ $serviceName }}
        port:
          number: {{ .Values.service.port }}
        subset: v1
      weight: 90
    - destination:
        host: {{ $serviceName }}
        port:
          number: {{ .Values.service.port }}
        subset: v2
      weight: 10