{{- $serviceName := include "member.name" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}-secret
type: Opaque
data:
{{- $files := .Files }}
{{- range tuple "secret/mysql.yaml" }}
{{- $files.Get . | nindent 2 }}
{{- end }}